# -*- coding: utf-8 -*-
"""VisionScopeAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AfBVXA7ptzZIQ-4U2MXJFMfgyOMTEWd3
"""

!pip install ultralytics gradio plotly -q

# ==========================================================
# VISIONSCOPE AI — Real-Time Object Detection Dashboard
# YOLOv8 + Gradio | Built by Areef Rasool
# ==========================================================

# Run this first in Colab:
# !pip install ultralytics gradio plotly -q

import gradio as gr
import plotly.express as px
import pandas as pd
import numpy as np
import cv2
import time
from PIL import Image
from ultralytics import YOLO
from collections import Counter

# ==========================================================
# LOAD MODEL
# ==========================================================

model = YOLO("yolov8n.pt")  # nano version — fast, good for demo/Colab

CLASS_NAMES = model.names  # dict of class id -> name

# ==========================================================
# GLOBAL STATS STORAGE
# ==========================================================

detection_log = []

# ==========================================================
# CSS — Dark glassmorphism theme (CodeWire Pro style)
# ==========================================================

css = """

.gradio-container{
    max-width:1600px !important;
    background:
    radial-gradient(circle at top left,#0f172a,#020617);
    color:white;
}

/* HERO */

.hero{

    position:relative;
    overflow:hidden;

    padding:80px 50px;

    border-radius:32px;

    background:
    linear-gradient(
        135deg,
        rgba(15,23,42,0.95),
        rgba(3,7,18,0.95)
    );

    border:
    1px solid rgba(34,211,238,0.12);

    text-align:center;

    box-shadow:
    0 20px 60px rgba(0,0,0,.4);
}

/* glow */

.hero::after{

    content:"";

    position:absolute;

    width:400px;
    height:400px;

    background:
    radial-gradient(
        rgba(251,191,36,.15),
        transparent
    );

    top:-100px;
    right:-100px;

    border-radius:50%;
}

.hero-tag{

    display:inline-block;

    padding:10px 20px;

    border-radius:999px;

    background:
    rgba(251,191,36,.08);

    border:
    1px solid rgba(251,191,36,.20);

    color:#fbbf24;

    font-size:12px;

    letter-spacing:2px;
}

.hero h1{

    margin-top:25px;

    font-size:72px;

    font-weight:900;

    line-height:1;

    background:
    linear-gradient(
        90deg,
        #ffffff,
        #fbbf24
    );

    -webkit-background-clip:text;
    color:transparent;
}

.hero h2{

    color:#cbd5e1;

    font-size:28px;

    margin-top:10px;

    font-weight:500;
}

.hero p{

    max-width:700px;

    margin:auto;

    margin-top:20px;

    color:#94a3b8;

    font-size:17px;
}

.hero-stats{

    display:flex;

    justify-content:center;

    gap:50px;

    margin-top:35px;
}

.hero-stats span{

    display:block;

    font-size:26px;

    color:#fbbf24;

    font-weight:700;
}

.hero-stats small{

    color:#94a3b8;
}

/* KPI */

.kpi-grid{
    display:grid;
    grid-template-columns:repeat(4,1fr);
    gap:18px;
}

.kpi-card{

    background:
    linear-gradient(
        145deg,
        rgba(15,23,42,.95),
        rgba(30,41,59,.85)
    );

    border:
    1px solid rgba(255,255,255,.06);

    backdrop-filter:blur(20px);

    border-radius:24px;

    padding:28px;
}

.kpi-card:hover{

    transform:translateY(-5px);

    box-shadow:
    0 0 20px rgba(34,211,238,0.2);
}

.kpi-card h2{

    color:#fbbf24;

    font-size:34px;
}

/* SECTIONS */

.section-card{

    background:
    rgba(15,23,42,0.85);

    border:
    1px solid rgba(255,255,255,0.06);

    border-radius:22px;

    padding:25px;
}

/* BUTTONS */

button{

    background:
    linear-gradient(
        90deg,
        #f59e0b,
        #fbbf24
    ) !important;

    border:none !important;

    font-weight:700 !important;

    border-radius:14px !important;
}

/* IMAGE OUTPUT */

img{
    border-radius:18px !important;
}

/* NAVBAR */

.navbar{

display:flex;
justify-content:space-between;
align-items:center;

padding:20px 30px;

margin-bottom:20px;

background:
rgba(255,255,255,.03);

border-radius:18px;

border:
1px solid rgba(255,255,255,.05);

backdrop-filter: blur(12px);
}

.navbar-left{

font-size:22px;
font-weight:800;

background:
linear-gradient(
90deg,
#ffffff,
#fbbf24
);

-webkit-background-clip:text;
color:transparent;
}

.navbar-right{
color:#94a3b8;
font-size:14px;
}

"""

# ==========================================================
# KPI GENERATOR
# ==========================================================

def generate_kpi_cards(objects=0, classes=0, conf="0%", speed="0 ms"):

    return f"""
    <div class="kpi-grid">

        <div class="kpi-card">
            <h2>{objects}</h2>
            <p>Objects Detected</p>
        </div>

        <div class="kpi-card">
            <h2>{classes}</h2>
            <p>Unique Classes</p>
        </div>

        <div class="kpi-card">
            <h2>{conf}</h2>
            <p>Avg Confidence</p>
        </div>

        <div class="kpi-card">
            <h2>{speed}</h2>
            <p>Inference Time</p>
        </div>

    </div>
    """

# ==========================================================
# DETECTION FUNCTION (IMAGE)
# ==========================================================

def detect_objects(image, confidence, selected_classes):

    if image is None:
        return (
            None,
            "<div class='section-card'><h2>⚠️ Upload an image first</h2></div>",
            generate_kpi_cards(),
            None,
            None
        )

    start = time.time()

    class_ids = None
    if selected_classes:
        class_ids = [
            k for k, v in CLASS_NAMES.items() if v in selected_classes
        ]

    results = model.predict(
        image,
        conf=confidence,
        classes=class_ids,
        verbose=False
    )

    elapsed = (time.time() - start) * 1000

    result = results[0]
    annotated = result.plot()
    annotated = cv2.cvtColor(annotated, cv2.COLOR_BGR2RGB)

    boxes = result.boxes

    if boxes is None or len(boxes) == 0:

        report = """
        <div class='section-card'>
            <h2>🔍 No Objects Detected</h2>
            <p>Try lowering the confidence threshold or removing class filters.</p>
        </div>
        """

        return (
            annotated,
            report,
            generate_kpi_cards(0, 0, "0%", f"{elapsed:.0f} ms"),
            None,
            None
        )

    detected_classes = [CLASS_NAMES[int(c)] for c in boxes.cls]
    confidences = [float(c) for c in boxes.conf]

    class_counts = Counter(detected_classes)
    avg_conf = (sum(confidences) / len(confidences)) * 100

    # build per-class breakdown table
    rows = "".join(
        f"<tr><td>{cls}</td><td>{count}</td></tr>"
        for cls, count in class_counts.most_common()
    )

    report = f"""
    <div class='section-card'>
        <h2>🎯 Detection Summary</h2>
        <p>Total Objects: <b>{len(detected_classes)}</b></p>
        <p>Unique Classes: <b>{len(class_counts)}</b></p>
        <p>Average Confidence: <b>{avg_conf:.1f}%</b></p>
        <table style="width:100%; margin-top:10px; color:white; border-collapse:collapse;">
            <tr style="text-align:left; color:#94a3b8;">
                <th>Class</th><th>Count</th>
            </tr>
            {rows}
        </table>
    </div>
    """

    kpi_html = generate_kpi_cards(
        len(detected_classes),
        len(class_counts),
        f"{avg_conf:.1f}%",
        f"{elapsed:.0f} ms"
    )

    # class distribution pie chart
    pie_fig = px.pie(
        names=list(class_counts.keys()),
        values=list(class_counts.values()),
        hole=0.55,
        title="Class Distribution"
    )
    pie_fig.update_layout(template="plotly_dark", height=380)

    # confidence bar chart per detection
    bar_fig = px.bar(
        x=list(range(1, len(confidences) + 1)),
        y=[c * 100 for c in confidences],
        labels={"x": "Detection #", "y": "Confidence (%)"},
        title="Per-Detection Confidence",
        color=detected_classes
    )
    bar_fig.update_layout(template="plotly_dark", height=380)

    # log this run for history chart
    detection_log.append({
        "run": len(detection_log) + 1,
        "objects": len(detected_classes),
        "avg_conf": avg_conf
    })

    return annotated, report, kpi_html, pie_fig, bar_fig

# ==========================================================
# DETECTION HISTORY CHART
# ==========================================================

def detection_history_chart():

    if not detection_log:
        fig = px.line(title="No detection history yet")
        fig.update_layout(template="plotly_dark", height=320)
        return fig

    df = pd.DataFrame(detection_log)

    fig = px.line(
        df,
        x="run",
        y="objects",
        markers=True,
        title="Objects Detected Per Run"
    )
    fig.update_layout(template="plotly_dark", height=320)

    return fig

# ==========================================================
# APP START
# ==========================================================

with gr.Blocks(css=css, theme=gr.themes.Soft()) as app:

    gr.HTML("""

    <div class="navbar">

    <div class="navbar-left">
        🎯 VisionScope AI
    </div>

    <div class="navbar-right">
        YOLOv8 • Analytics • Detection
    </div>

</div>

   <div class="hero">

    <div class="hero-tag">
        ● COMPUTER VISION PLATFORM
    </div>

    <h1>
        VisionScope AI
    </h1>

    <h2>
        Real-Time Visual Intelligence Engine
    </h2>

    <p>
        Detect, analyze and visualize objects with
        enterprise-grade AI powered by YOLOv8.
    </p>

    <div class="hero-stats">

        <div>
            <span>80+</span>
            <small>Object Classes</small>
        </div>

        <div>
            <span>YOLOv8</span>
            <small>Detection Engine</small>
        </div>

        <div>
            <span>Real-Time</span>
            <small>Inference</small>
        </div>

    </div>

</div>

    """)

    dashboard_cards = gr.HTML(value=generate_kpi_cards())

    gr.Markdown("""
## 🎯 AI Detection Console
Monitor detected objects, confidence metrics,
and visual analytics in real time.
""")

    with gr.Row():

        with gr.Column(scale=1):

            input_image = gr.Image(
                label="Upload Image",
                type="numpy"
            )

            confidence_slider = gr.Slider(
                minimum=0.1,
                maximum=1.0,
                value=0.4,
                step=0.05,
                label="Confidence Threshold"
            )

            class_filter = gr.Dropdown(
                choices=sorted(list(CLASS_NAMES.values())),
                multiselect=True,
                label="Filter Classes (leave empty for all)"
            )

            detect_btn = gr.Button(
                "🔍 Run Detection",
                variant="primary"
            )

        with gr.Column(scale=1):

            output_image = gr.Image(
                label="Detection Result"
            )

    detection_report = gr.HTML()

    with gr.Row():

        with gr.Column(scale=1):
            class_pie_chart = gr.Plot(label="Class Distribution")

        with gr.Column(scale=1):
            confidence_bar_chart = gr.Plot(label="Confidence per Detection")

    detect_btn.click(
        detect_objects,
        [input_image, confidence_slider, class_filter],
        [output_image, detection_report, dashboard_cards, class_pie_chart, confidence_bar_chart]
    )

    # ------------------------------------------------------
    # DETECTION HISTORY
    # ------------------------------------------------------

    with gr.Accordion("📊 Detection History", open=False):

        history_chart = gr.Plot()

        refresh_history_btn = gr.Button("🔄 Refresh History")

        refresh_history_btn.click(
            detection_history_chart,
            None,
            history_chart
        )

    # ------------------------------------------------------
    # WEBCAM SNAPSHOT MODE
    # ------------------------------------------------------

    with gr.Accordion("📷 Webcam Snapshot Detection", open=False):

        webcam_input = gr.Image(
            label="Take a Photo",
            sources=["webcam"],
            type="numpy"
        )

        webcam_conf = gr.Slider(
            minimum=0.1,
            maximum=1.0,
            value=0.4,
            step=0.05,
            label="Confidence Threshold"
        )

        webcam_output = gr.Image(label="Detection Result")
        webcam_report = gr.HTML()

        webcam_btn = gr.Button("🔍 Detect from Webcam")

        def webcam_detect(image, confidence):
            result = detect_objects(image, confidence, [])
            return result[0], result[1]

        webcam_btn.click(
            webcam_detect,
            [webcam_input, webcam_conf],
            [webcam_output, webcam_report]
        )

    # ------------------------------------------------------
    # FOOTER
    # ------------------------------------------------------

    gr.HTML("""

    <hr>

<center>

<h2>VISIONSCOPE AI</h2>

<p>
Advanced Computer Vision Intelligence Platform
</p>

<p>
Built by Areef Rasool
</p>

</center>

    """)

# ==========================================================
# APP LAUNCH
# ==========================================================

app.launch()